///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String dashboardCloud = 'assets/images/dashboard/cloud.png';
  static const String dashboardOrder = 'assets/images/dashboard/order.png';
  static const String imagesShoppingCart = 'assets/images/shopping_cart.png';
  static const String imagesWarning = 'assets/images/warning.png';

}
