///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String categoriesBookImg = 'assets/images/categories/book_img.png';
  static const String categoriesCosmetics = 'assets/images/categories/cosmetics.png';
  static const String categoriesElectronics = 'assets/images/categories/electronics.png';
  static const String categoriesFashion = 'assets/images/categories/fashion.png';
  static const String categoriesMobiles = 'assets/images/categories/mobiles.png';
  static const String categoriesPc = 'assets/images/categories/pc.png';
  static const String categoriesShoes = 'assets/images/categories/shoes.png';
  static const String categoriesWatch = 'assets/images/categories/watch.png';
  static const String dashboardCloud = 'assets/images/dashboard/cloud.png';
  static const String dashboardOrder = 'assets/images/dashboard/order.png';
  static const String imagesEmptySearch = 'assets/images/empty_search.png';
  static const String imagesError = 'assets/images/error.png';
  static const String imagesRoundedMap = 'assets/images/rounded_map.png';
  static const String imagesShoppingCart = 'assets/images/shopping_cart.png';
  static const String imagesWarning = 'assets/images/warning.png';

}
